### ISSUE TITLE
error double files dll ( XNA, monogame) thanks

### ISSUE THREAD

**Issue by MORYis** [htmlcoderexe/3DGame#2]
![xna_mono](https://user-images.githubusercontent.com/12050950/120402679-017b1200-c343-11eb-8626-8c1dacdf344a.png)

**Comment by htmlcoderexe** [comment]
This is strange, can you try to remove this reference then readd it? I am not super familiar with this kind of conflict - maybe you need to install/get Monogame stuff properly before this works properly.

**Comment by MORYis** [comment]
is work good thanks i have install new version
