### ISSUE TITLE
good work ( ç quoi la version de monogame dans le projet?)

### ISSUE THREAD

**Issue by MORYis** [htmlcoderexe/3DGame#3]
bonjour est ce que tu peux créer une vidéo explique comment exécuter le programme , merci bc

**Comment by htmlcoderexe** [comment]
Hmm, I don't do videos and don't think it would help much. This is the actual DLL referenced on my system, version 3.6.0.1625, revised no later than 01.03.2017:

![bilde](https://user-images.githubusercontent.com/34088724/120909173-ac0c7100-c672-11eb-98c8-18dd798179fd.png)

**Comment by MORYis** [comment]
is work for my thanks
